pestenegra = "\nPeste Negra: 50 milhões de mortos (Europa e Ásia) – 1333 a 1351 \n História: A peste bubônica ganhou o nome de peste negra por causa da pior epidemia que atingiu a Europa, no século 14. Ela foi sendo combatida à medida que se melhorou a higiene e o saneamento das cidades, diminuindo a população de ratos urbanos \n Contaminação: Causada pela bactéria Yersinia pestis, comum em roedores como o rato. É transmitida para o homem pela pulga desses animais contaminados \n Sintomas: Inflamação dos gânglios linfáticos, seguida de tremedeiras, dores localizadas, apatia, vertigem e febre alta \n Tratamento: À base de antibióticos. Sem tratamento, mata em 60% dos casos"

colera = "\nCólera: Centenas de milhares de mortos – 1817 a 1824 \n História – Conhecida desde a Antiguidade, teve sua primeira epidemia global em 1817. Desde então, o vibrião colérico (Vibrio cholerae) sofreu diversas mutações, causando novos ciclos epidêmicos de tempos em tempos \n Contaminação – Por meio de água ou alimentos contaminados \n Sintomas – A bactéria se multiplica no intestino e elimina uma toxina que provoca diarréia intensa \n Tratamento – À base de antibióticos. A vacina disponível é de baixa eficácia (50% de imunização)"

tuberculose = "\nTuberculose: 1 bilhão de mortos – 1850 a 1950 \n  História – Sinais da doença foram encontrados em esqueletos de 7 000 anos atrás. O combate foi acelerado em 1882, depois da identificação do bacilo de Koch, causador da tuberculose. Nas últimas década, ressurgiu com força nos países pobres, incluindo o Brasil, e como doença oportunista nos pacientes de Aids \n Contaminação – Altamente contagiosa, transmite-se de pessoa para pessoa, através das vias respiratórias \n Sintomas – Ataca principalmente os pulmões \n Tratamento – À base de antibióticos, o paciente é curado em até seis meses"

variola = "\nVaríola: 300 milhões de mortos – 1896 a 1980 \n A doença atormentou a humanidade por mais de 3 000 anos. Até figurões como o faraó egípcio Ramsés II, a rainha Maria II da Inglaterra e o rei Luís XV da França tiveram a temida “bixiga”. A vacina foi descoberta em 1796 \n Contaminação - O Orthopoxvírus variolae era transmitido de pessoa para pessoa, geralmente por meio das vias respiratórias \n Sintomas -  Febre, seguida de erupções na garganta, na boca e no rosto. Posteriormente, pústulas que podiam deixar cicatrizes no corpo \n Tratamentos -  Erradicada do planeta desde 1980, após campanha de vacinação em massa " 

espanhola = "\nGripe Espanhola: 20 milhões de mortos – 1918 a 1919 \n História – O vírus Influenza é um dos maiores carrascos da humanidade. A mais grave epidemia foi batizada de gripe espanhola, embora tenha feito vítimas no mundo todo. No Brasil, matou o presidente Rodrigues Alves \n Contaminação – Propaga-se pelo ar, por meio de gotículas de saliva e espirros \n Sintomas – Fortes dores de cabeça e no corpo, calafrios e inchaço dos pulmões \n Tratamento – O vírus está em permanente mutação, por isso o homem nunca está imune. As vacinas antigripais previnem a contaminação com formas já conhecidas do vírus"

febreamarela = "\nFebre Amarela: 30 000 mortos (Etiópia) – 1960 a 1962 \n História – O Flavivírus, que tem uma versão urbana e outra silvestre, já causou grandes epidemias na África e nas Américas \n Contaminação – A vítima é picada pelo mosquito transmissor, que picou antes uma pessoa infectada com o vírus \n Sintomas – Febre alta, mal-estar, cansaço, calafrios, náuseas, vômitos e diarréia. 85% dos pacientes recupera-se em três ou quatro dias. Os outros podem ter sintomas mais graves, que podem levá-los à morte \n Tratamento – Existe vacina, que pode ser aplicada a partir dos 12 meses de idade e renovada a cada dez anos"

sarampo = "\n Sarampo: 6 milhões de mortos por ano – Até 1963 \n História – Era uma das causas principais de mortalidade infantil até a descoberta da primeira vacina, em 1963. Com o passar dos anos, a vacina foi aperfeiçoada, e a doença foi erradicada em vários países \nContaminação – Altamente contagioso, o sarampo é causado pelo vírus Morbillivirus, propagado por meio das secreções mucosas (como a saliva, por exemplo) de indivíduos doentes \n Sintomas – Pequenas erupções avermelhadas na pele, febre alta, dor de cabeça, mal-estar e inflamação das vias respiratórias \n Tratamento – Existe vacina, aplicada aos nove meses de idade e reaplicada aos 15 meses"

aids = "\nAIDS: 22 milhões de mortos – Desde 1981 \n História – A doença foi identificada em 1981, nos Estados Unidos, e desde então foi considerada uma epidemia pela Organização Mundial de Saúde \n Contaminação – O vírus HIV é transmitido através do sangue, do esperma, da secreção vaginal e do leite materno \n Sintomas – Destrói o sistema imunológico, deixando o organismo frágil a doenças causadas por outros vírus, bactérias, parasitas e células cancerígenas \n Tratamento – Não existe cura. Os soropositivos são tratados com coquetéis de drogas que inibem a multiplicação do vírus, mas não o eliminam do organismo"

covid = "\nCovid-19: Com mais de 5 Milhoes de mortes - A Covid-19 é uma infecção respiratória aguda causada pelo coronavírus SARS-CoV-2, potencialmente grave, de elevada transmissibilidade e de distribuição global.\n O SARS-CoV-2 é um betacoronavírus descoberto em amostras de lavado broncoalveolar obtidas de pacientes com pneumonia de causa desconhecida na cidade de Wuhan, província de Hubei, China, em dezembro de 2019. Pertence ao subgênero Sarbecovírus da família Coronaviridae e é o sétimo coronavírus conhecido a infectar seres humanos.\n Os coronavírus são uma grande família de vírus comuns em muitas espécies diferentes de animais, incluindo o homem, camelos, gado, gatos e morcegos. Raramente os coronavírus de animais podem infectar pessoas e depois se espalhar entre seres humanos como já ocorreu com o MERS-CoV e o SARS-CoV-2. Até o momento, não foi definido o reservatório silvestre do SARS-CoV-2."